services:
  web:
    build: .
    command: >
      sh -c "sleep 5 &&
             python manage.py makemigrations core &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py seed_data &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      DEBUG: "1"
      SECRET_KEY: "django-insecure-key-12345"
      JWT_SECRET_KEY: "jwt-secret-key-12345"
      DB_NAME: "auth_db"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      DB_HOST: "db"
      DB_PORT: "5432"  
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: "auth_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5433:5432"  